config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'tweets#index'

  # ユーザーリソース
  resource :user_profile, only: %i[edit update], controller: 'users'
  resources :users, only: %i[show] do
    member do
      get :retweets, :replies, :likes
    end
    resource :relationships, only: %i[create destroy]
  end

  # tweets リソース
  resources :tweets, only: %i[index show create] do
    collection do
      get :following
    end
    resources :replies, only: [:create]
    resource :likes, only: %i[create destroy]
    resource :retweets, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # bookmarks リソース
  resources :bookmarks, only: [:index]

  # メッセージ機能
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end

  # 通知
  resources :notifications, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_many :retweets, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :notifications, dependent: :destroy
  # 自己結合（コメント）
  belongs_to :parent, class_name: 'Tweet', optional: true
  has_many :replies, class_name: 'Tweet', foreign_key: 'parent_id', dependent: :destroy, inverse_of: :parent
  # バリデーション
  validates :content, presence: true, length: { maximum: 140 }
end

app/controllers/tweets_controller.rb
# frozen_string_literal: true

class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweets, only: %i[index]
  before_action :set_tweet, only: %i[show]

  def index; end

  def show
    @replies = @tweet.replies.page(params[:page])
  end

  def create
    @tweet = current_user.tweets.build(tweet_params)
    if @tweet.save
      redirect_to root_path, flash: { success: 'ツイートできました' }
    else
      set_tweets
      render :index, status: :unprocessable_entity
    end
  end

  def following
    @tweets = current_user.following_tweets.page(params[:page])
    render :index
  end

  def tweet_params
    params.require(:tweet).permit(:content, :image)
  end

  def set_tweets
    @tweets = current_user.all_tweets.page(params[:page])
  end

  def set_tweet
    @tweet = Tweet.find(params[:id])
  end
end

app/views/tweets/_tweet.html.slim
div.list-group-item.border-bottom
  .d-flex.mt-2
    / アバター
    .me-3
      = link_to user_path(tweet.user) do
        = image_tag tweet.user.display_image, width: 40, height: 40, class: "rounded-circle"
    / ツイート投稿内容
    = link_to tweet_path(tweet), class: "text-dark text-decoration-none" do
      strong.mb-0.me-3
        = tweet.user.name.present? ? tweet.user.name : "undefined"
      small.text-muted
        = tweet.created_at.strftime('%Y/%m/%d %H:%M')
      p
        = simple_format sanitize(tweet.content)
      - if tweet.image.attached?
        .mt-3
          = image_tag tweet.image, width: 240, class: 'img-fluid'
    - unless tweet.user == current_user
      .dropend.ms-auto
        i.bi.bi-three-dots.text-dark type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false"
        ul.dropdown-menu aria-labelledby="dropdownMenuButton1" style="padding: 10px;"
          li
            = link_to user_relationships_path(user_id: tweet.user), class: "dropdown-item", data: { turbo_method: current_user.following?(tweet.user) ? :delete : :post } do
              | #{tweet.user.name}さんを #{current_user.following?(tweet.user) ? 'フォロー解除' : 'フォロー'}
          li
            .dropdown-item style="cursor: pointer;"
              | 閉じる

  / ツイートの操作（リツイート、いいね、コメント）
  .d-flex.mt-3.ms-5
    .me-5
      = link_to tweet_path(tweet), class: 'me-2', style: "color: inherit;"  do
        i.bi.bi-chat
      span
        = tweet.replies.count
    .me-5
      - if tweet.retweets.find_by(user_id: current_user.id)
        = link_to tweet_retweets_path(tweet_id: tweet.id), data: { turbo_method: :delete }, class: 'me-2', style: "color: green;" do
          i.bi.bi-arrow-repeat
        span style="color: green;"
          = tweet.retweets.count
      - else
        = link_to tweet_retweets_path(tweet_id: tweet.id), data: { turbo_method: :post }, class: 'me-2', style: "color: inherit;" do
          i.bi.bi-arrow-repeat
        span
          = tweet.retweets.count
    .me-5
      - if tweet.likes.find_by(user_id: current_user.id)
        = link_to tweet_likes_path(tweet_id: tweet.id), data: { turbo_method: :delete }, class: 'me-2', style: "color: rgb(249, 24, 128);"  do
          i.bi.bi-heart-fill
        span style="color: rgb(249, 24, 128);"
          = tweet.likes.count
      - else
        = link_to tweet_likes_path(tweet_id: tweet.id), data: { turbo_method: :post }, class: 'me-2', style: "color: rgb(249, 24, 128);"  do
          i.bi.bi-heart
        span
          = tweet.likes.count
    .me-5
      - if tweet.bookmarks.find_by(user_id: current_user.id)
        = link_to tweet_bookmarks_path(tweet_id: tweet.id), data: { turbo_method: :delete }, class: 'me-2' do
          i.bi.bi-bookmark-fill
      - else
        = link_to tweet_bookmarks_path(tweet_id: tweet.id), data: { turbo_method: :post }, class: 'me-2' do
          i.bi.bi-bookmark

app/views/tweets/_tweets.html.slim
- unless tweets.nil? || tweets.empty?
  - tweets.each do |tweet|
    = render 'tweets/tweet', tweet: tweet

  / ページネーション
  nav.mt-3
    = paginate tweets, theme: 'bootstrap-5'

app/views/tweets/index.html.slim
nav.nav-pills
  ul.nav.border-gray.border-bottom.text-center
    li.nav-item.col-6 class="#{current_page?(root_path) ? 'fw-bold text-muted' : ''}"
      = link_to 'おすすめ', root_path, class: 'nav-link link-dark border-gray border-end'
    li.nav-item.col-6 class="#{current_page?(following_tweets_path) ? 'fw-bold text-muted' : ''}"
      = link_to 'フォロー中', following_tweets_path, class: 'nav-link link-dark'

.d-flex.mt-3
  / アバター
  .me-3
    = link_to user_path(current_user) do
      = image_tag current_user.display_image, width: 40, height: 40, class: "rounded-circle"
  / ツイート投稿フォーム
  = form_with model: @tweet || Tweet.new, local: true, class: "flex-fill" do |f|
    - if @tweet&.errors&.any?
      .alert.alert-danger
        p
          = "#{@tweet.errors.count}つのエラーにより、更新が失敗しました"
        ul
          - @tweet.errors.full_messages.each do |message|
            li= message
    .form-group
      = f.text_area :content, class: "form-control mb-2", placeholder: "いまどうしてる？"
      .d-flex.align-items-center.justify-content-between.mt-3
        .d-flex.align-items-center
          = f.file_field :image, id: 'file-input', class: "file-input"
          label.file-label for="file-input"
            i.bi.bi-image.text-primary class="mr-1" style="font-size: 1.5em;"
        = f.submit "ツイートする", class: "btn btn-primary"

/ ツイートの一覧
div.list-group.mt-3
  = render 'tweets/tweets', tweets: @tweets

app/views/tweets/show.html.slim
= render 'tweets/tweet', tweet: @tweet

/ コメント投稿フォーム

.d-flex.mt-3
  / アバター
  .me-3
    = link_to user_path(current_user) do
      = image_tag current_user.display_image, width: 40, height: 40, class: "rounded-circle"
  = form_with model: Tweet.new, url: tweet_replies_path(@tweet), local: true, class: "mt-3 flex-fill" do |f|
    - if @tweet&.errors&.any?
      .alert.alert-danger
        p
          = "#{@tweet.errors.count}つのエラーにより、更新が失敗しました"
        ul
          - @tweet.errors.full_messages.each do |message|
            li= message
    .form-group
      = f.text_area :content, class: "form-control mb-2", placeholder: "返信をツイート"
      .d-flex.align-items-center.justify-content-between.mt-3
        .d-flex.align-items-center
          = f.file_field :image, id: 'file-input', class: "file-input"
          label.file-label for="file-input"
            i.bi.bi-image.text-primary class="mr-1" style="font-size: 1.5em;"
        = f.submit "返信", class: "btn btn-primary"

/ コメント一覧
div.list-group.mt-3
  = render 'tweets/tweets', tweets:  @replies