config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'tweets#index'

  # ユーザーリソース
  resource :user_profile, only: %i[edit update], controller: 'users'
  resources :users, only: %i[show] do
    member do
      get :retweets, :replies, :likes
    end
    resource :relationships, only: %i[create destroy]
  end

  # tweets リソース
  resources :tweets, only: %i[index show create] do
    collection do
      get :following
    end
    resources :replies, only: [:create]
    resource :likes, only: %i[create destroy]
    resource :retweets, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # bookmarks リソース
  resources :bookmarks, only: [:index]

  # メッセージ機能
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end

  # 通知
  resources :notifications, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include TweetsConcern

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable,
         :omniauthable, omniauth_providers: [:github]

  # Relationships
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy,
                                  inverse_of: :follower
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy,
                                   inverse_of: :followed
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ツイートに関するアソシエーション
  has_many :tweets, dependent: :destroy
  has_many :replies, class_name: 'Tweet', foreign_key: 'parent_id', dependent: :destroy, inverse_of: :parent
  has_many :retweets, dependent: :destroy
  has_many :retweet_tweets, through: :retweets, source: :tweet
  has_many :likes, dependent: :destroy
  has_many :like_tweets, through: :likes, source: :tweet
  has_many :bookmarks, dependent: :destroy
  # 中間テーブルのbookmarksを経由して、tweetテーブルを参照する。中間テーブルであるbookmarksのcreated_atを降順に並べ替える。
  has_many :bookmarked_tweets, -> { order('bookmarks.created_at DESC') }, through: :bookmarks, source: :tweet

  # ユーザーが送信者となっている会話
  has_many :conversations_as_sender, foreign_key: :sender_id, class_name: 'Conversation', dependent: :destroy,
                                     inverse_of: :sender
  # ユーザーが受信者となっている会話
  has_many :conversations_as_recipient, foreign_key: :recipient_id, class_name: 'Conversation', dependent: :destroy,
                                        inverse_of: :recipient
  # 通知に関するアソシエーション
  has_many :active_notifications, class_name: 'Notification', foreign_key: 'action_user_id', dependent: :destroy,
                                  inverse_of: 'action_user'
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'passive_user_id', dependent: :destroy,
                                   inverse_of: 'passive_user'

  # ユーザーのバリデーション
  validates :tel, presence: true, unless: :from_omniauth?
  validates :birthday, presence: true, unless: :from_omniauth?
  validates :name, length: { maximum: 20 }
  validates :description, length: { maximum: 200 }
  validates :place, length: { maximum: 50 }
  validates :website, length: { maximum: 100 },
                      format: { with: /\A#{URI::DEFAULT_PARSER.make_regexp(%w[http https])}\z/, allow_blank: true }

  # フロフィール画像
  has_one_attached :profile_image
  has_one_attached :header_image

  def display_image
    if profile_image.attached?
      profile_image
    else
      'https://source.unsplash.com/phIFdC6lA4E/40x40'
    end
  end

  def self.find_for_github_oauth(auth)
    # GitHubアカウントがあれば返す
    user = User.where(provider: auth.provider, uid: auth.uid).first

    if user
      user.update!(name: auth.info.name) if user.name.nil?
      return user
    end

    # 既存ユーザーがいれば返す、いなければ新規作成する
    user = User.where(email: auth.info.email).first_or_initialize
    assign_github_attributes(user, auth)
    user.save!
    user
  end

  def self.assign_github_attributes(user, auth)
    if user.new_record? # 新しいユーザーの場合
      user.assign_attributes(
        email: auth.info.email, password: Devise.friendly_token[0, 20],
        provider: auth.provider, uid: auth.uid, name: auth.info.name
      )
      user.skip_confirmation! # 確認メールをスキップ
    else # 既存のユーザーにGitHubの情報を追加
      user.update!(provider: auth.provider, uid: auth.uid)
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def from_omniauth?
    provider.present? && uid.present?
  end

  # フォローに関するメソッド
  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  # DMに関するメソッド
  def conversations
    Conversation.where(sender_id: id).or(Conversation.where(recipient_id: id))
  end

  def find_or_create_conversation_with(other_user)
    Conversation.between(id, other_user.id).first ||
      Conversation.find_or_create_by(sender_id: id, recipient_id: other_user.id)
  end

  # 通知に関するメソッド（ツイートに関する）
  def create_notification(tweet, action)
    return if id == tweet.user_id

    notification = active_notifications.new(
      tweet_id: tweet.id,
      passive_user_id: tweet.user_id,
      action: action
    )
    # バリデーション通れば、保存して通知メール送信
    return unless notification.save

    NotificationMailer.notification_email(tweet.user).deliver_later
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

module Users
  class ConfirmationsController < Devise::ConfirmationsController
    # GET /resource/confirmation/new
    # def new
    #   super
    # end

    # POST /resource/confirmation
    # def create
    #   super
    # end

    # GET /resource/confirmation?confirmation_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after resending confirmation instructions.
    # def after_resending_confirmation_instructions_path_for(resource_name)
    #   super(resource_name)
    # end

    # The path used after confirmation.
    # def after_confirmation_path_for(resource_name, resource)
    #   super(resource_name, resource)
    # end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    # You should configure your model like this:
    # devise :omniauthable, omniauth_providers: [:twitter]

    # You should also create an action method in this controller like this:
    # def twitter
    # end

    # More info at:
    # https://github.com/heartcombo/devise#omniauth

    def github
      @user = User.find_for_github_oauth(request.env['omniauth.auth'])

      if @user.persisted? # データベースに保存されていればログイン成功
        sign_in_and_redirect @user, event: :authentication
        set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
      else # ログイン失敗
        session['devise.github_data'] = request.env['omniauth.auth']
        redirect_to new_user_registration_url
      end
    end

    def failure
      redirect_to root_path
    end

    # GET|POST /resource/auth/twitter
    # def passthru
    #   super
    # end

    # GET|POST /users/auth/twitter/callback
    # def failure
    #   super
    # end

    # protected

    # The path used when OmniAuth fails
    # def after_omniauth_failure_path_for(scope)
    #   super(scope)
    # end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

module Users
  class PasswordsController < Devise::PasswordsController
    # GET /resource/password/new
    # def new
    #   super
    # end

    # POST /resource/password
    # def create
    #   super
    # end

    # GET /resource/password/edit?reset_password_token=abcdef
    # def edit
    #   super
    # end

    # PUT /resource/password
    # def update
    #   super
    # end

    # protected

    # def after_resetting_password_path_for(resource)
    #   super(resource)
    # end

    # The path used after sending reset password instructions
    # def after_sending_reset_password_instructions_path_for(resource_name)
    #   super(resource_name)
    # end
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    before_action :configure_sign_up_params, only: [:create]
    # before_action :configure_account_update_params, only: [:update]

    def build_resource(hash = {})
      # uid&providerはユニークなので、uidを自動生成
      hash[:uid] = User.create_unique_string
      super
    end

    # GET /resource/sign_up
    # def new
    #   super
    # end

    # POST /resource
    # def create
    #   super
    # end

    # GET /resource/edit
    # def edit
    #   super
    # end

    # PUT /resource
    # def update
    #   super
    # end

    # DELETE /resource
    # def destroy
    #   super
    # end

    # GET /resource/cancel
    # Forces the session data which is usually expired after sign
    # in to be expired now. This is useful if the user wants to
    # cancel oauth signing in/up in the middle of the process,
    # removing all OAuth session data.
    # def cancel
    #   super
    # end

    protected

    # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: %i[name tel birthday profile_image])
    end

    # ユーザー情報更新時にパスワード入力なしで更新できるようにする
    def update_resource(resource, params)
      return super if params['password']&.present?

      resource.update_without_password(params.except('current_password'))
    end

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_account_update_params
    #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
    # end

    # The path used after sign up.
    # def after_sign_up_path_for(resource)
    #   super(resource)
    # end

    # The path used after sign up for inactive accounts.
    # def after_inactive_sign_up_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    # before_action :configure_sign_in_params, only: [:create]

    # GET /resource/sign_in
    # def new
    #   super
    # end

    # POST /resource/sign_in
    # def create
    #   super
    # end

    # DELETE /resource/sign_out
    # def destroy
    #   super
    # end

    # protected

    # If you have extra params to permit, append them to the sanitizer.
    # def configure_sign_in_params
    #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
    # end
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show retweets replies likes]
  before_action :set_current_user, only: %i[edit update]

  def show
    @tweets = @user.ordered_tweets.page(params[:page])
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if current_user.update(user_params)
      redirect_to current_user, flash: { success: 'プロフィールを変更できました' }
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def retweets
    @tweets = @user.ordered_retweets.page(params[:page])
    render :show
  end

  def replies
    @tweets = @user.ordered_replies.page(params[:page])
    render :show
  end

  def likes
    @tweets = @user.ordered_likes.page(params[:page])
    render :show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :header_image, :description, :place, :website, :birthday)
  end
end

app/views/users/edit.html.slim
h2 
  = 'プロフィール編集'
= form_with(model: @user, url: user_profile_path, local: true, html: { class: 'row g-3 pb-4' }) do |form|
  - if @user.errors.any?
    .alert.alert-danger
      p
        = "#{@user.errors.count}つのエラーにより、更新が失敗しました"
      ul
        - @user.errors.full_messages.each do |message|
          li= message

  .col-12
    = form.label :name, '名前', class: 'form-label'
    = form.text_field :name, class: 'form-control'

  .col-12
    = form.label :profile_image, 'プロフィール画像', class: 'form-label'
    = form.file_field :profile_image, class: 'form-control', onchange: 'loadFile(event, "profile_output")'
    - if @user.profile_image.attached?
      = image_tag(@user.profile_image, id: 'profile_output', class: 'img-thumbnail w-25')

  .col-12
    = form.label :header_image, 'ヘッダー画像', class: 'form-label'
    = form.file_field :header_image, class: 'form-control', onchange: 'loadFile(event, "header_output")'
    - if @user.header_image.attached?
      = image_tag(@user.header_image, id: 'header_output', class: 'img-thumbnail w-25')

  .col-12
    = form.label :description, '説明', class: 'form-label'
    = form.text_area :description, class: 'form-control'

  .col-12
    = form.label :place, '場所', class: 'form-label'
    = form.text_field :place, class: 'form-control'

  .col-12
    = form.label :website, 'ウェブサイト', class: 'form-label'
    = form.text_field :website, class: 'form-control'

  .col-12
    = form.label :birthday, '誕生日', class: 'form-label'
    = form.date_field :birthday, class: 'form-control'

  .col-12
    .d-grid.gap-2.d-md-flex.justify-content-md-end
      = link_to 'キャンセル', user_path(current_user), class: 'btn btn-secondary'
      = form.submit '更新', class: 'btn btn-primary me-md-2'

/ 画像を非同期で表示させるロジック
javascript:
  function loadFile(event, outputId) {
    const output = document.getElementById(outputId);
    output.src = URL.createObjectURL(event.target.files[0]);
    output.onload = function() {
      URL.revokeObjectURL(output.src)
    }
  };

app/views/users/show.html.slim
.card
  - if @user.header_image.attached?
    = image_tag @user.header_image, class: "card-img-top", height: "150"
  - else
    = image_tag "https://source.unsplash.com/phIFdC6lA4E/40x40", class: "card-img-top", height: "150"
  .card-body
    - if current_user == @user
      p.text-end
        = link_to 'プロフィールを編集', edit_user_profile_path
    .d-flex.flex-column
      - if @user.profile_image.attached?
        = image_tag @user.profile_image, class: "rounded-circle", width: "150"
      - else
        = image_tag "https://source.unsplash.com/phIFdC6lA4E/40x40", class: "rounded-circle", width: "150"
      .d-flex.justify-content-between
        h4.card-title.mt-2 = @user.name.present? ? @user.name : "undefined"
        - unless @user == current_user
          .d-flex
            = button_to conversations_path(user_id: @user.id), method: :post, class: 'btn btn-primary me-2' do
              i.bi.bi-envelope-fill
            = button_to user_relationships_path(user_id: @user), class: "btn #{current_user.following?(@user) ?  "btn-outline-dark" : "btn-dark"}", method: current_user.following?(@user) ? :delete : :post  do
              | #{current_user.following?(@user) ? 'フォロー中' : 'フォロー'}

      .text-muted = @user.email
      - if @user.description.present?
        p.card-text = simple_format(@user.description)
      .d-flex.text-muted.small
        - if @user.place.present?
          span.me-4
            i.bi.bi-geo-fill
            = @user.place
        - if @user.website.present?
          span.me-4
            i.bi.bi-link-45deg
            = link_to @user.website, @user.website, target: "_blank"
        - if @user.birthday.present?
          span
            i.bi.bi-gift
            = @user.birthday.strftime('%Y/%m/%d')
      p.small.text-muted
        i.bi.bi-calendar
        = " #{@user.created_at.strftime('%Y年%m月')}からTwitterを利用しています"
      p.small
        b = " #{@user.following.count} "
        | フォロー中: 
        b = " #{@user.followers.count} "
        | フォロワー中

/ ツイートのタブ
.nav.nav-pills.mt-3
  = link_to "ツイート", user_path(@user), class: "nav-link #{'active' if current_page?(user_path(@user))}"
  = link_to "リツイート", retweets_user_path(@user), class: "nav-link #{'active' if current_page?(retweets_user_path(@user))}"
  = link_to "コメント", replies_user_path(@user), class: "nav-link #{'active' if current_page?(replies_user_path(@user))}"
  = link_to "いいね", likes_user_path(@user), class: "nav-link #{'active' if current_page?(likes_user_path(@user))}"

/ ツイートの一覧
.tab-content.list-group
  #tweets.tab-pane.fade.show.active
    = render 'tweets/tweets', tweets: @tweets.presence