config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root to: 'tweets#index'

  # ユーザーリソース
  resource :user_profile, only: %i[edit update], controller: 'users'
  resources :users, only: %i[show] do
    member do
      get :retweets, :replies, :likes
    end
    resource :relationships, only: %i[create destroy]
  end

  # tweets リソース
  resources :tweets, only: %i[index show create] do
    collection do
      get :following
    end
    resources :replies, only: [:create]
    resource :likes, only: %i[create destroy]
    resource :retweets, only: %i[create destroy]
    resource :bookmarks, only: %i[create destroy]
  end
  # bookmarks リソース
  resources :bookmarks, only: [:index]

  # メッセージ機能
  resources :conversations, only: %i[index show create] do
    resources :messages, only: %i[create]
  end

  # 通知
  resources :notifications, only: [:index]

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/views/layouts/_header.html.slim
nav.navbar.navbar-expand-sm.navbar-light.border-gray.border-bottom
  .container
    = link_to root_path, class:"text-decoration-none" do
      = image_tag 'logo.png', class: 'navbar-brand-logo', style:"width: 1rem; margin-right: 1rem"
      span = 'Twitterクローン'
    - flash.each do |key, value|
      span class="alert alert-#{key} p-1 m-0 ms-4"
        = value
    button.navbar-toggler type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon
    .collapse.navbar-collapse#navbarSupportedContent
      ul.navbar-nav.ms-auto.mb-2.mb-lg-0
        - if user_signed_in?
          li.nav-item
            = button_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'btn btn-outline-primary'
        - elsif controller_name == 'registrations'
          li.nav-item
            = button_to 'ログイン', new_user_session_path, class: 'btn btn-outline-primary me-3'

app/views/layouts/_sidebar.html.slim
ul.list-unstyled.fs-5
  = render partial: 'layouts/sidebar_link', locals: {path: root_path, icon: 'bi-house', text: 'ホーム'}
  / = render partial: 'layouts/sidebar_link', locals: {path: user_registration_path, icon: 'bi-search', text: '話題を検索'}
  = render partial: 'layouts/sidebar_link', locals: {path: notifications_path, icon: 'bi-bell', text: '通知'}
  = render partial: 'layouts/sidebar_link', locals: {path: conversations_path(), icon: 'bi-envelope', text: 'メッセージ'}
  = render partial: 'layouts/sidebar_link', locals: {path: bookmarks_path, icon: 'bi-bookmark', text: 'ブックマーク'}
  / = render partial: 'layouts/sidebar_link', locals: {path: user_registration_path, icon: 'bi-gem', text: 'Twitter Blue'}
  = render partial: 'layouts/sidebar_link', locals: {path: user_path(current_user), icon: 'bi-person', text: 'プロフィール'}
  / = render partial: 'layouts/sidebar_link', locals: {path: user_registration_path, icon: 'bi-three-dots', text: 'もっと見る'}
  / = render partial: 'layouts/sidebar_link', locals: {path: user_registration_path, icon: 'bi-twitter', text: 'ツイートする'}

app/views/layouts/_sidebar_link.html.slim
li.ps-1
  = link_to local_assigns[:path], class: 'text-decoration-none link-dark d-block p-3' do
    i class="bi #{local_assigns[:icon]} #{current_page?(local_assigns[:path]) ? 'text-primary' : ''}"
    span.ms-2 class="#{current_page?(local_assigns[:path]) ? 'text-primary fw-bold' : ''}"
      = local_assigns[:text]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Twitter
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", defer: true
  body
    = render partial: 'layouts/header'
    .container
      .row.flex-nowrap
        - if user_signed_in?
          .col-auto.p-0.border-gray.border-end
            = render partial: 'layouts/sidebar'
        .col-8.border-gray.border-end
          = yield